### ISSUE TITLE
Putting the fine-tuned model in Hugging Face for easy access

### ISSUE THREAD

**Issue by MNIKIEMA** [RUCKBReasoning/schema-filter#1]
Hello @lihaoyang-ruc , 
Thank you for your exceptional work. For the convenience of others, could you please share the fine-tuned checkpoint on Hugging Face (or a Google Drive link)? This would make it easily accessible for everyone involved.

**Comment by lihaoyang-ruc** [comment]
Certainly. Please wait a few days because I am busy these days. Thank you for your understanding.

**Comment by lihaoyang-ruc** [comment]
We have uploaded our model on Google Drive, please refer to https://drive.google.com/file/d/1xzNvv5h-ZjhjOOZ-ePv1xg_n3YbUNLWi/view?usp=sharing

We have also updated README, thank you for your suggestions!

**Comment by MNIKIEMA** [comment]
Thanks, I have downloaded the checkpoint.
