### ISSUE TITLE
请问下CodeS论文中的这个实验，有没有结合schema filter 和Value Retriever等操作？

### ISSUE THREAD

**Issue by xingyuma618** [RUCKBReasoning/schema-filter#4]
![微信截图_20240521173416](https://github.com/RUCKBReasoning/text2sql-schema-filter/assets/17610546/644e2b5d-7d24-4568-a68e-c14dc2da9a81)

请问下CodeS这里的codellama的实验结果，是结合 schema filter 和Value Retriever之后跑出结果吗？因为我之前也跑过code llama的实验，没有做schema filter等操作的情况下（即全部表格一起写在prompt中），7b的EX指标只有75%左右。所以想排查下效果差的原因。期待您的回复！

**Comment by lihaoyang-ruc** [comment]
是的，这里的SFT LLama的性能是加了schema filter 和Value Retriever。

SFT LLama和SFT CodeS的唯一不同就是把LLama基座更换成了CodeS，他们使用同样的prompt构建策略。

**Comment by xingyuma618** [comment]
好的。明白了。谢谢您

**Comment by xingyuma618** [comment]
不好意思，再请教个问题，请问这里是用的huggingface 里的meta-llama/Llama-2-7b版本模型对吗？没有用Code Llama 以及llama-chat那些版本对吧？

**Comment by 798610929** [comment]
请问能给一下它的prompt构建模板吗？
